package javacorba.CorbaServiceModule;


/**
* javacorba/CorbaServiceModule/CorbaServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/Git/CorpIS/CorpIS.Java/CorpIS.Java.Corba/corbaService.idl
* 9 Ноябрь 2013 г. 3:32:15 MSK
*/

public interface CorbaServiceOperations 
{
  float changeBalance (int id, float diff);
  String getName (int id);
  float getBalance (int id);
  int[] getAllCustomerIds ();
} // interface CorbaServiceOperations
