package javacorba.CorbaServiceModule;


/**
* javacorba/CorbaServiceModule/CorbaServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/Git/CorpIS/CorpIS.Java/CorpIS.Java.Corba/corbaService.idl
* 9 Ноябрь 2013 г. 3:32:15 MSK
*/

public abstract class CorbaServicePOA extends org.omg.PortableServer.Servant
 implements javacorba.CorbaServiceModule.CorbaServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("changeBalance", new java.lang.Integer (0));
    _methods.put ("getName", new java.lang.Integer (1));
    _methods.put ("getBalance", new java.lang.Integer (2));
    _methods.put ("getAllCustomerIds", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaServiceModule/CorbaService/changeBalance
       {
         int id = in.read_long ();
         float diff = in.read_float ();
         float $result = (float)0;
         $result = this.changeBalance (id, diff);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // CorbaServiceModule/CorbaService/getName
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.getName (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // CorbaServiceModule/CorbaService/getBalance
       {
         int id = in.read_long ();
         float $result = (float)0;
         $result = this.getBalance (id);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // CorbaServiceModule/CorbaService/getAllCustomerIds
       {
         int $result[] = null;
         $result = this.getAllCustomerIds ();
         out = $rh.createReply();
         javacorba.CorbaServiceModule.customerIdsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaServiceModule/CorbaService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CorbaService _this() 
  {
    return CorbaServiceHelper.narrow(
    super._this_object());
  }

  public CorbaService _this(org.omg.CORBA.ORB orb) 
  {
    return CorbaServiceHelper.narrow(
    super._this_object(orb));
  }


} // class CorbaServicePOA
