package javacorba.CorbaServiceModule;


/**
* javacorba/CorbaServiceModule/CorbaServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/Git/CorpIS/CorpIS.Java/CorpIS.Java.Corba/corbaService.idl
* 9 Ноябрь 2013 г. 3:32:15 MSK
*/

abstract public class CorbaServiceHelper
{
  private static String  _id = "IDL:CorbaServiceModule/CorbaService:1.0";

  public static void insert (org.omg.CORBA.Any a, javacorba.CorbaServiceModule.CorbaService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static javacorba.CorbaServiceModule.CorbaService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (javacorba.CorbaServiceModule.CorbaServiceHelper.id (), "CorbaService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static javacorba.CorbaServiceModule.CorbaService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CorbaServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, javacorba.CorbaServiceModule.CorbaService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static javacorba.CorbaServiceModule.CorbaService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof javacorba.CorbaServiceModule.CorbaService)
      return (javacorba.CorbaServiceModule.CorbaService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      javacorba.CorbaServiceModule._CorbaServiceStub stub = new javacorba.CorbaServiceModule._CorbaServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static javacorba.CorbaServiceModule.CorbaService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof javacorba.CorbaServiceModule.CorbaService)
      return (javacorba.CorbaServiceModule.CorbaService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      javacorba.CorbaServiceModule._CorbaServiceStub stub = new javacorba.CorbaServiceModule._CorbaServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
