package javacorba.CorbaServiceModule;


/**
* javacorba/CorbaServiceModule/CorbaService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/Git/CorpIS/CorpIS.Java/CorpIS.Java.Corba/corbaService.idl
* 9 Ноябрь 2013 г. 3:32:15 MSK
*/

public interface CorbaService extends CorbaServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaService
