package javacorba.CorbaServiceModule;

/**
* javacorba/CorbaServiceModule/CorbaServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/Git/CorpIS/CorpIS.Java/CorpIS.Java.Corba/corbaService.idl
* 9 Ноябрь 2013 г. 3:32:15 MSK
*/

public final class CorbaServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public javacorba.CorbaServiceModule.CorbaService value = null;

  public CorbaServiceHolder ()
  {
  }

  public CorbaServiceHolder (javacorba.CorbaServiceModule.CorbaService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = javacorba.CorbaServiceModule.CorbaServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    javacorba.CorbaServiceModule.CorbaServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return javacorba.CorbaServiceModule.CorbaServiceHelper.type ();
  }

}
