package javacorba.CorbaServiceModule;


/**
* javacorba/CorbaServiceModule/customerIdsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/Git/CorpIS/CorpIS.Java/CorpIS.Java.Corba/corbaService.idl
* 9 Ноябрь 2013 г. 3:32:15 MSK
*/

public final class customerIdsHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public customerIdsHolder ()
  {
  }

  public customerIdsHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = javacorba.CorbaServiceModule.customerIdsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    javacorba.CorbaServiceModule.customerIdsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return javacorba.CorbaServiceModule.customerIdsHelper.type ();
  }

}
