//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpISTask1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string NAME { get; set; }
        public float BALANCE { get; set; }
        public long ID { get; set; }
    }
}
